### ISSUE TITLE
SNR Calculation!

### ISSUE THREAD

**Issue by NimaDolatabadi** [smousavi05/SAC_data_processing#1]
I the very first line of your code you have defined **e**  

> e=` awk 'END{ print NR}' evfullist2.dat`
what is this file, are you listing all the events? or maybe you are considering part of files name! should it be SAC type data? 
I need an example of your data so that I could be able to repeat these on my data as well.
a picture or syntaxes will do the job.
Regrads

**Comment by smousavi05** [comment]
this file contains the SAC file names. Unfortunately, I do not have the example files at the moment.
